export const types = {
	login: '[Auth] Login',
	logout: '[Auth] Logout',
	uiSetError: '[UI] set error',
	uiRemoveError: '[UI] Remove error',
	uiStartLoading: '[UI] Start loading',
	uiFinishLoading: '[UI] Finish laoding',
	notesAddNew: '[Notes] New Note',
	notesActive: '[Notes] Set Active Note',
	notesLoad: '[Notes] Load Notes',
	notesUpdated: '[Notes] Update Notes',
	notesFileUrl: '[Notes] Update image url',
	notesDelete: '[Notes] Delete note',
	notesLogoutCleaning: '[Notes] Logout',
};
